export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CATALOG_ROUTE = '/'
export const CAR_ROUTE = '/car'
export const ORDER_ROUTE = '/order'